/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeChungToiRouteImport } from './routes/ve-chung-toi'
import { Route as TimKiemRouteImport } from './routes/tim-kiem'
import { Route as ThucPhamRouteImport } from './routes/thuc-pham'
import { Route as TheThaoRouteImport } from './routes/the-thao'
import { Route as SurveyAuditRouteImport } from './routes/survey-audit'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyPhamRouteImport } from './routes/my-pham'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as HuongDanSizeRouteImport } from './routes/huong-dan-size'
import { Route as GioHangRouteImport } from './routes/gio-hang'
import { Route as DouyinRouteImport } from './routes/douyin'
import { Route as DanhMucRouteImport } from './routes/danh-muc'
import { Route as DamNguRouteImport } from './routes/dam-ngu'
import { Route as DamDiChoiRouteImport } from './routes/dam-di-choi'
import { Route as CongSoRouteImport } from './routes/cong-so'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SanPhamIdRouteImport } from './routes/san-pham.$id'
import { Route as AuthenticatedWithdrawalsRouteImport } from './routes/_authenticated/withdrawals'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedVeganRouteImport } from './routes/_authenticated/vegan'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTiersRouteImport } from './routes/_authenticated/tiers'
import { Route as AuthenticatedSurveyStatsRouteImport } from './routes/_authenticated/survey-stats'
import { Route as AuthenticatedStoresRouteImport } from './routes/_authenticated/stores'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPromosRouteImport } from './routes/_authenticated/promos'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHotelRouteImport } from './routes/_authenticated/hotel'
import { Route as AuthenticatedFashionRouteImport } from './routes/_authenticated/fashion'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAffiliateRouteImport } from './routes/_authenticated/affiliate'
import { Route as ApiPublicBillingWebhookRouteImport } from './routes/api/public/billing-webhook'
import { Route as AuthenticatedVeganTemplesRouteImport } from './routes/_authenticated/vegan.temples'
import { Route as AuthenticatedVeganProductsRouteImport } from './routes/_authenticated/vegan.products'
import { Route as AuthenticatedVeganPosRouteImport } from './routes/_authenticated/vegan.pos'
import { Route as AuthenticatedVeganOrdersRouteImport } from './routes/_authenticated/vegan.orders'
import { Route as AuthenticatedVeganCharityRouteImport } from './routes/_authenticated/vegan.charity'
import { Route as AuthenticatedSuperAdminModulesRouteImport } from './routes/_authenticated/super-admin.modules'
import { Route as AuthenticatedHotelStayRouteImport } from './routes/_authenticated/hotel.stay'
import { Route as AuthenticatedHotelRequestsRouteImport } from './routes/_authenticated/hotel.requests'
import { Route as AuthenticatedHotelOperationsRouteImport } from './routes/_authenticated/hotel.operations'
import { Route as AuthenticatedHotelGuestPortalRouteImport } from './routes/_authenticated/hotel.guest-portal'
import { Route as AuthenticatedHotelChatRouteImport } from './routes/_authenticated/hotel.chat'
import { Route as AuthenticatedFashionReturnsRouteImport } from './routes/_authenticated/fashion.returns'
import { Route as AuthenticatedFashionAiFittingRouteImport } from './routes/_authenticated/fashion.ai-fitting'
import { Route as AuthenticatedFashionAccessoriesRouteImport } from './routes/_authenticated/fashion.accessories'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'

const VeChungToiRoute = VeChungToiRouteImport.update({
  id: '/ve-chung-toi',
  path: '/ve-chung-toi',
  getParentRoute: () => rootRouteImport,
} as any)
const TimKiemRoute = TimKiemRouteImport.update({
  id: '/tim-kiem',
  path: '/tim-kiem',
  getParentRoute: () => rootRouteImport,
} as any)
const ThucPhamRoute = ThucPhamRouteImport.update({
  id: '/thuc-pham',
  path: '/thuc-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const TheThaoRoute = TheThaoRouteImport.update({
  id: '/the-thao',
  path: '/the-thao',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyAuditRoute = SurveyAuditRouteImport.update({
  id: '/survey-audit',
  path: '/survey-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPhamRoute = MyPhamRouteImport.update({
  id: '/my-pham',
  path: '/my-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongDanSizeRoute = HuongDanSizeRouteImport.update({
  id: '/huong-dan-size',
  path: '/huong-dan-size',
  getParentRoute: () => rootRouteImport,
} as any)
const GioHangRoute = GioHangRouteImport.update({
  id: '/gio-hang',
  path: '/gio-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const DouyinRoute = DouyinRouteImport.update({
  id: '/douyin',
  path: '/douyin',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhMucRoute = DanhMucRouteImport.update({
  id: '/danh-muc',
  path: '/danh-muc',
  getParentRoute: () => rootRouteImport,
} as any)
const DamNguRoute = DamNguRouteImport.update({
  id: '/dam-ngu',
  path: '/dam-ngu',
  getParentRoute: () => rootRouteImport,
} as any)
const DamDiChoiRoute = DamDiChoiRouteImport.update({
  id: '/dam-di-choi',
  path: '/dam-di-choi',
  getParentRoute: () => rootRouteImport,
} as any)
const CongSoRoute = CongSoRouteImport.update({
  id: '/cong-so',
  path: '/cong-so',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamIdRoute = SanPhamIdRouteImport.update({
  id: '/san-pham/$id',
  path: '/san-pham/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithdrawalsRoute =
  AuthenticatedWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVeganRoute = AuthenticatedVeganRouteImport.update({
  id: '/vegan',
  path: '/vegan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTiersRoute = AuthenticatedTiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSurveyStatsRoute =
  AuthenticatedSurveyStatsRouteImport.update({
    id: '/survey-stats',
    path: '/survey-stats',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStoresRoute = AuthenticatedStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPromosRoute = AuthenticatedPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHotelRoute = AuthenticatedHotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFashionRoute = AuthenticatedFashionRouteImport.update({
  id: '/fashion',
  path: '/fashion',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAffiliateRoute = AuthenticatedAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicBillingWebhookRoute = ApiPublicBillingWebhookRouteImport.update({
  id: '/api/public/billing-webhook',
  path: '/api/public/billing-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVeganTemplesRoute =
  AuthenticatedVeganTemplesRouteImport.update({
    id: '/temples',
    path: '/temples',
    getParentRoute: () => AuthenticatedVeganRoute,
  } as any)
const AuthenticatedVeganProductsRoute =
  AuthenticatedVeganProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedVeganRoute,
  } as any)
const AuthenticatedVeganPosRoute = AuthenticatedVeganPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedVeganRoute,
} as any)
const AuthenticatedVeganOrdersRoute =
  AuthenticatedVeganOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedVeganRoute,
  } as any)
const AuthenticatedVeganCharityRoute =
  AuthenticatedVeganCharityRouteImport.update({
    id: '/charity',
    path: '/charity',
    getParentRoute: () => AuthenticatedVeganRoute,
  } as any)
const AuthenticatedSuperAdminModulesRoute =
  AuthenticatedSuperAdminModulesRouteImport.update({
    id: '/super-admin/modules',
    path: '/super-admin/modules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHotelStayRoute = AuthenticatedHotelStayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => AuthenticatedHotelRoute,
} as any)
const AuthenticatedHotelRequestsRoute =
  AuthenticatedHotelRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedHotelRoute,
  } as any)
const AuthenticatedHotelOperationsRoute =
  AuthenticatedHotelOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedHotelRoute,
  } as any)
const AuthenticatedHotelGuestPortalRoute =
  AuthenticatedHotelGuestPortalRouteImport.update({
    id: '/guest-portal',
    path: '/guest-portal',
    getParentRoute: () => AuthenticatedHotelRoute,
  } as any)
const AuthenticatedHotelChatRoute = AuthenticatedHotelChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedHotelRoute,
} as any)
const AuthenticatedFashionReturnsRoute =
  AuthenticatedFashionReturnsRouteImport.update({
    id: '/returns',
    path: '/returns',
    getParentRoute: () => AuthenticatedFashionRoute,
  } as any)
const AuthenticatedFashionAiFittingRoute =
  AuthenticatedFashionAiFittingRouteImport.update({
    id: '/ai-fitting',
    path: '/ai-fitting',
    getParentRoute: () => AuthenticatedFashionRoute,
  } as any)
const AuthenticatedFashionAccessoriesRoute =
  AuthenticatedFashionAccessoriesRouteImport.update({
    id: '/accessories',
    path: '/accessories',
    getParentRoute: () => AuthenticatedFashionRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cong-so': typeof CongSoRoute
  '/dam-di-choi': typeof DamDiChoiRoute
  '/dam-ngu': typeof DamNguRoute
  '/danh-muc': typeof DanhMucRoute
  '/douyin': typeof DouyinRoute
  '/gio-hang': typeof GioHangRoute
  '/huong-dan-size': typeof HuongDanSizeRoute
  '/lien-he': typeof LienHeRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/my-pham': typeof MyPhamRoute
  '/profile': typeof ProfileRoute
  '/survey-audit': typeof SurveyAuditRoute
  '/the-thao': typeof TheThaoRoute
  '/thuc-pham': typeof ThucPhamRoute
  '/tim-kiem': typeof TimKiemRoute
  '/ve-chung-toi': typeof VeChungToiRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fashion': typeof AuthenticatedFashionRouteWithChildren
  '/hotel': typeof AuthenticatedHotelRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pos': typeof AuthenticatedPosRoute
  '/products': typeof AuthenticatedProductsRoute
  '/promos': typeof AuthenticatedPromosRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/survey-stats': typeof AuthenticatedSurveyStatsRoute
  '/tiers': typeof AuthenticatedTiersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vegan': typeof AuthenticatedVeganRouteWithChildren
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/fashion/accessories': typeof AuthenticatedFashionAccessoriesRoute
  '/fashion/ai-fitting': typeof AuthenticatedFashionAiFittingRoute
  '/fashion/returns': typeof AuthenticatedFashionReturnsRoute
  '/hotel/chat': typeof AuthenticatedHotelChatRoute
  '/hotel/guest-portal': typeof AuthenticatedHotelGuestPortalRoute
  '/hotel/operations': typeof AuthenticatedHotelOperationsRoute
  '/hotel/requests': typeof AuthenticatedHotelRequestsRoute
  '/hotel/stay': typeof AuthenticatedHotelStayRoute
  '/super-admin/modules': typeof AuthenticatedSuperAdminModulesRoute
  '/vegan/charity': typeof AuthenticatedVeganCharityRoute
  '/vegan/orders': typeof AuthenticatedVeganOrdersRoute
  '/vegan/pos': typeof AuthenticatedVeganPosRoute
  '/vegan/products': typeof AuthenticatedVeganProductsRoute
  '/vegan/temples': typeof AuthenticatedVeganTemplesRoute
  '/api/public/billing-webhook': typeof ApiPublicBillingWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cong-so': typeof CongSoRoute
  '/dam-di-choi': typeof DamDiChoiRoute
  '/dam-ngu': typeof DamNguRoute
  '/danh-muc': typeof DanhMucRoute
  '/douyin': typeof DouyinRoute
  '/gio-hang': typeof GioHangRoute
  '/huong-dan-size': typeof HuongDanSizeRoute
  '/lien-he': typeof LienHeRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/my-pham': typeof MyPhamRoute
  '/profile': typeof ProfileRoute
  '/survey-audit': typeof SurveyAuditRoute
  '/the-thao': typeof TheThaoRoute
  '/thuc-pham': typeof ThucPhamRoute
  '/tim-kiem': typeof TimKiemRoute
  '/ve-chung-toi': typeof VeChungToiRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fashion': typeof AuthenticatedFashionRouteWithChildren
  '/hotel': typeof AuthenticatedHotelRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pos': typeof AuthenticatedPosRoute
  '/products': typeof AuthenticatedProductsRoute
  '/promos': typeof AuthenticatedPromosRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/survey-stats': typeof AuthenticatedSurveyStatsRoute
  '/tiers': typeof AuthenticatedTiersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vegan': typeof AuthenticatedVeganRouteWithChildren
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/fashion/accessories': typeof AuthenticatedFashionAccessoriesRoute
  '/fashion/ai-fitting': typeof AuthenticatedFashionAiFittingRoute
  '/fashion/returns': typeof AuthenticatedFashionReturnsRoute
  '/hotel/chat': typeof AuthenticatedHotelChatRoute
  '/hotel/guest-portal': typeof AuthenticatedHotelGuestPortalRoute
  '/hotel/operations': typeof AuthenticatedHotelOperationsRoute
  '/hotel/requests': typeof AuthenticatedHotelRequestsRoute
  '/hotel/stay': typeof AuthenticatedHotelStayRoute
  '/super-admin/modules': typeof AuthenticatedSuperAdminModulesRoute
  '/vegan/charity': typeof AuthenticatedVeganCharityRoute
  '/vegan/orders': typeof AuthenticatedVeganOrdersRoute
  '/vegan/pos': typeof AuthenticatedVeganPosRoute
  '/vegan/products': typeof AuthenticatedVeganProductsRoute
  '/vegan/temples': typeof AuthenticatedVeganTemplesRoute
  '/api/public/billing-webhook': typeof ApiPublicBillingWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/cong-so': typeof CongSoRoute
  '/dam-di-choi': typeof DamDiChoiRoute
  '/dam-ngu': typeof DamNguRoute
  '/danh-muc': typeof DanhMucRoute
  '/douyin': typeof DouyinRoute
  '/gio-hang': typeof GioHangRoute
  '/huong-dan-size': typeof HuongDanSizeRoute
  '/lien-he': typeof LienHeRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/my-pham': typeof MyPhamRoute
  '/profile': typeof ProfileRoute
  '/survey-audit': typeof SurveyAuditRoute
  '/the-thao': typeof TheThaoRoute
  '/thuc-pham': typeof ThucPhamRoute
  '/tim-kiem': typeof TimKiemRoute
  '/ve-chung-toi': typeof VeChungToiRoute
  '/_authenticated/affiliate': typeof AuthenticatedAffiliateRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fashion': typeof AuthenticatedFashionRouteWithChildren
  '/_authenticated/hotel': typeof AuthenticatedHotelRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/promos': typeof AuthenticatedPromosRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/_authenticated/stores': typeof AuthenticatedStoresRoute
  '/_authenticated/survey-stats': typeof AuthenticatedSurveyStatsRoute
  '/_authenticated/tiers': typeof AuthenticatedTiersRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/vegan': typeof AuthenticatedVeganRouteWithChildren
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/fashion/accessories': typeof AuthenticatedFashionAccessoriesRoute
  '/_authenticated/fashion/ai-fitting': typeof AuthenticatedFashionAiFittingRoute
  '/_authenticated/fashion/returns': typeof AuthenticatedFashionReturnsRoute
  '/_authenticated/hotel/chat': typeof AuthenticatedHotelChatRoute
  '/_authenticated/hotel/guest-portal': typeof AuthenticatedHotelGuestPortalRoute
  '/_authenticated/hotel/operations': typeof AuthenticatedHotelOperationsRoute
  '/_authenticated/hotel/requests': typeof AuthenticatedHotelRequestsRoute
  '/_authenticated/hotel/stay': typeof AuthenticatedHotelStayRoute
  '/_authenticated/super-admin/modules': typeof AuthenticatedSuperAdminModulesRoute
  '/_authenticated/vegan/charity': typeof AuthenticatedVeganCharityRoute
  '/_authenticated/vegan/orders': typeof AuthenticatedVeganOrdersRoute
  '/_authenticated/vegan/pos': typeof AuthenticatedVeganPosRoute
  '/_authenticated/vegan/products': typeof AuthenticatedVeganProductsRoute
  '/_authenticated/vegan/temples': typeof AuthenticatedVeganTemplesRoute
  '/api/public/billing-webhook': typeof ApiPublicBillingWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cong-so'
    | '/dam-di-choi'
    | '/dam-ngu'
    | '/danh-muc'
    | '/douyin'
    | '/gio-hang'
    | '/huong-dan-size'
    | '/lien-he'
    | '/login'
    | '/lookbook'
    | '/my-pham'
    | '/profile'
    | '/survey-audit'
    | '/the-thao'
    | '/thuc-pham'
    | '/tim-kiem'
    | '/ve-chung-toi'
    | '/affiliate'
    | '/billing'
    | '/customers'
    | '/dashboard'
    | '/fashion'
    | '/hotel'
    | '/inventory'
    | '/marketing'
    | '/orders'
    | '/pos'
    | '/products'
    | '/promos'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/stores'
    | '/survey-stats'
    | '/tiers'
    | '/users'
    | '/vegan'
    | '/wallet'
    | '/withdrawals'
    | '/san-pham/$id'
    | '/customers/$id'
    | '/fashion/accessories'
    | '/fashion/ai-fitting'
    | '/fashion/returns'
    | '/hotel/chat'
    | '/hotel/guest-portal'
    | '/hotel/operations'
    | '/hotel/requests'
    | '/hotel/stay'
    | '/super-admin/modules'
    | '/vegan/charity'
    | '/vegan/orders'
    | '/vegan/pos'
    | '/vegan/products'
    | '/vegan/temples'
    | '/api/public/billing-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cong-so'
    | '/dam-di-choi'
    | '/dam-ngu'
    | '/danh-muc'
    | '/douyin'
    | '/gio-hang'
    | '/huong-dan-size'
    | '/lien-he'
    | '/login'
    | '/lookbook'
    | '/my-pham'
    | '/profile'
    | '/survey-audit'
    | '/the-thao'
    | '/thuc-pham'
    | '/tim-kiem'
    | '/ve-chung-toi'
    | '/affiliate'
    | '/billing'
    | '/customers'
    | '/dashboard'
    | '/fashion'
    | '/hotel'
    | '/inventory'
    | '/marketing'
    | '/orders'
    | '/pos'
    | '/products'
    | '/promos'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/stores'
    | '/survey-stats'
    | '/tiers'
    | '/users'
    | '/vegan'
    | '/wallet'
    | '/withdrawals'
    | '/san-pham/$id'
    | '/customers/$id'
    | '/fashion/accessories'
    | '/fashion/ai-fitting'
    | '/fashion/returns'
    | '/hotel/chat'
    | '/hotel/guest-portal'
    | '/hotel/operations'
    | '/hotel/requests'
    | '/hotel/stay'
    | '/super-admin/modules'
    | '/vegan/charity'
    | '/vegan/orders'
    | '/vegan/pos'
    | '/vegan/products'
    | '/vegan/temples'
    | '/api/public/billing-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/cong-so'
    | '/dam-di-choi'
    | '/dam-ngu'
    | '/danh-muc'
    | '/douyin'
    | '/gio-hang'
    | '/huong-dan-size'
    | '/lien-he'
    | '/login'
    | '/lookbook'
    | '/my-pham'
    | '/profile'
    | '/survey-audit'
    | '/the-thao'
    | '/thuc-pham'
    | '/tim-kiem'
    | '/ve-chung-toi'
    | '/_authenticated/affiliate'
    | '/_authenticated/billing'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/fashion'
    | '/_authenticated/hotel'
    | '/_authenticated/inventory'
    | '/_authenticated/marketing'
    | '/_authenticated/orders'
    | '/_authenticated/pos'
    | '/_authenticated/products'
    | '/_authenticated/promos'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/shifts'
    | '/_authenticated/stores'
    | '/_authenticated/survey-stats'
    | '/_authenticated/tiers'
    | '/_authenticated/users'
    | '/_authenticated/vegan'
    | '/_authenticated/wallet'
    | '/_authenticated/withdrawals'
    | '/san-pham/$id'
    | '/_authenticated/customers/$id'
    | '/_authenticated/fashion/accessories'
    | '/_authenticated/fashion/ai-fitting'
    | '/_authenticated/fashion/returns'
    | '/_authenticated/hotel/chat'
    | '/_authenticated/hotel/guest-portal'
    | '/_authenticated/hotel/operations'
    | '/_authenticated/hotel/requests'
    | '/_authenticated/hotel/stay'
    | '/_authenticated/super-admin/modules'
    | '/_authenticated/vegan/charity'
    | '/_authenticated/vegan/orders'
    | '/_authenticated/vegan/pos'
    | '/_authenticated/vegan/products'
    | '/_authenticated/vegan/temples'
    | '/api/public/billing-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  CongSoRoute: typeof CongSoRoute
  DamDiChoiRoute: typeof DamDiChoiRoute
  DamNguRoute: typeof DamNguRoute
  DanhMucRoute: typeof DanhMucRoute
  DouyinRoute: typeof DouyinRoute
  GioHangRoute: typeof GioHangRoute
  HuongDanSizeRoute: typeof HuongDanSizeRoute
  LienHeRoute: typeof LienHeRoute
  LoginRoute: typeof LoginRoute
  LookbookRoute: typeof LookbookRoute
  MyPhamRoute: typeof MyPhamRoute
  ProfileRoute: typeof ProfileRoute
  SurveyAuditRoute: typeof SurveyAuditRoute
  TheThaoRoute: typeof TheThaoRoute
  ThucPhamRoute: typeof ThucPhamRoute
  TimKiemRoute: typeof TimKiemRoute
  VeChungToiRoute: typeof VeChungToiRoute
  SanPhamIdRoute: typeof SanPhamIdRoute
  ApiPublicBillingWebhookRoute: typeof ApiPublicBillingWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ve-chung-toi': {
      id: '/ve-chung-toi'
      path: '/ve-chung-toi'
      fullPath: '/ve-chung-toi'
      preLoaderRoute: typeof VeChungToiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-kiem': {
      id: '/tim-kiem'
      path: '/tim-kiem'
      fullPath: '/tim-kiem'
      preLoaderRoute: typeof TimKiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thuc-pham': {
      id: '/thuc-pham'
      path: '/thuc-pham'
      fullPath: '/thuc-pham'
      preLoaderRoute: typeof ThucPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-thao': {
      id: '/the-thao'
      path: '/the-thao'
      fullPath: '/the-thao'
      preLoaderRoute: typeof TheThaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey-audit': {
      id: '/survey-audit'
      path: '/survey-audit'
      fullPath: '/survey-audit'
      preLoaderRoute: typeof SurveyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-pham': {
      id: '/my-pham'
      path: '/my-pham'
      fullPath: '/my-pham'
      preLoaderRoute: typeof MyPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huong-dan-size': {
      id: '/huong-dan-size'
      path: '/huong-dan-size'
      fullPath: '/huong-dan-size'
      preLoaderRoute: typeof HuongDanSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gio-hang': {
      id: '/gio-hang'
      path: '/gio-hang'
      fullPath: '/gio-hang'
      preLoaderRoute: typeof GioHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/douyin': {
      id: '/douyin'
      path: '/douyin'
      fullPath: '/douyin'
      preLoaderRoute: typeof DouyinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-muc': {
      id: '/danh-muc'
      path: '/danh-muc'
      fullPath: '/danh-muc'
      preLoaderRoute: typeof DanhMucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dam-ngu': {
      id: '/dam-ngu'
      path: '/dam-ngu'
      fullPath: '/dam-ngu'
      preLoaderRoute: typeof DamNguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dam-di-choi': {
      id: '/dam-di-choi'
      path: '/dam-di-choi'
      fullPath: '/dam-di-choi'
      preLoaderRoute: typeof DamDiChoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-so': {
      id: '/cong-so'
      path: '/cong-so'
      fullPath: '/cong-so'
      preLoaderRoute: typeof CongSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$id': {
      id: '/san-pham/$id'
      path: '/san-pham/$id'
      fullPath: '/san-pham/$id'
      preLoaderRoute: typeof SanPhamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdrawals': {
      id: '/_authenticated/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof AuthenticatedWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vegan': {
      id: '/_authenticated/vegan'
      path: '/vegan'
      fullPath: '/vegan'
      preLoaderRoute: typeof AuthenticatedVeganRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tiers': {
      id: '/_authenticated/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof AuthenticatedTiersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/survey-stats': {
      id: '/_authenticated/survey-stats'
      path: '/survey-stats'
      fullPath: '/survey-stats'
      preLoaderRoute: typeof AuthenticatedSurveyStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promos': {
      id: '/_authenticated/promos'
      path: '/promos'
      fullPath: '/promos'
      preLoaderRoute: typeof AuthenticatedPromosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hotel': {
      id: '/_authenticated/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof AuthenticatedHotelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fashion': {
      id: '/_authenticated/fashion'
      path: '/fashion'
      fullPath: '/fashion'
      preLoaderRoute: typeof AuthenticatedFashionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliate': {
      id: '/_authenticated/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AuthenticatedAffiliateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/billing-webhook': {
      id: '/api/public/billing-webhook'
      path: '/api/public/billing-webhook'
      fullPath: '/api/public/billing-webhook'
      preLoaderRoute: typeof ApiPublicBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vegan/temples': {
      id: '/_authenticated/vegan/temples'
      path: '/temples'
      fullPath: '/vegan/temples'
      preLoaderRoute: typeof AuthenticatedVeganTemplesRouteImport
      parentRoute: typeof AuthenticatedVeganRoute
    }
    '/_authenticated/vegan/products': {
      id: '/_authenticated/vegan/products'
      path: '/products'
      fullPath: '/vegan/products'
      preLoaderRoute: typeof AuthenticatedVeganProductsRouteImport
      parentRoute: typeof AuthenticatedVeganRoute
    }
    '/_authenticated/vegan/pos': {
      id: '/_authenticated/vegan/pos'
      path: '/pos'
      fullPath: '/vegan/pos'
      preLoaderRoute: typeof AuthenticatedVeganPosRouteImport
      parentRoute: typeof AuthenticatedVeganRoute
    }
    '/_authenticated/vegan/orders': {
      id: '/_authenticated/vegan/orders'
      path: '/orders'
      fullPath: '/vegan/orders'
      preLoaderRoute: typeof AuthenticatedVeganOrdersRouteImport
      parentRoute: typeof AuthenticatedVeganRoute
    }
    '/_authenticated/vegan/charity': {
      id: '/_authenticated/vegan/charity'
      path: '/charity'
      fullPath: '/vegan/charity'
      preLoaderRoute: typeof AuthenticatedVeganCharityRouteImport
      parentRoute: typeof AuthenticatedVeganRoute
    }
    '/_authenticated/super-admin/modules': {
      id: '/_authenticated/super-admin/modules'
      path: '/super-admin/modules'
      fullPath: '/super-admin/modules'
      preLoaderRoute: typeof AuthenticatedSuperAdminModulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hotel/stay': {
      id: '/_authenticated/hotel/stay'
      path: '/stay'
      fullPath: '/hotel/stay'
      preLoaderRoute: typeof AuthenticatedHotelStayRouteImport
      parentRoute: typeof AuthenticatedHotelRoute
    }
    '/_authenticated/hotel/requests': {
      id: '/_authenticated/hotel/requests'
      path: '/requests'
      fullPath: '/hotel/requests'
      preLoaderRoute: typeof AuthenticatedHotelRequestsRouteImport
      parentRoute: typeof AuthenticatedHotelRoute
    }
    '/_authenticated/hotel/operations': {
      id: '/_authenticated/hotel/operations'
      path: '/operations'
      fullPath: '/hotel/operations'
      preLoaderRoute: typeof AuthenticatedHotelOperationsRouteImport
      parentRoute: typeof AuthenticatedHotelRoute
    }
    '/_authenticated/hotel/guest-portal': {
      id: '/_authenticated/hotel/guest-portal'
      path: '/guest-portal'
      fullPath: '/hotel/guest-portal'
      preLoaderRoute: typeof AuthenticatedHotelGuestPortalRouteImport
      parentRoute: typeof AuthenticatedHotelRoute
    }
    '/_authenticated/hotel/chat': {
      id: '/_authenticated/hotel/chat'
      path: '/chat'
      fullPath: '/hotel/chat'
      preLoaderRoute: typeof AuthenticatedHotelChatRouteImport
      parentRoute: typeof AuthenticatedHotelRoute
    }
    '/_authenticated/fashion/returns': {
      id: '/_authenticated/fashion/returns'
      path: '/returns'
      fullPath: '/fashion/returns'
      preLoaderRoute: typeof AuthenticatedFashionReturnsRouteImport
      parentRoute: typeof AuthenticatedFashionRoute
    }
    '/_authenticated/fashion/ai-fitting': {
      id: '/_authenticated/fashion/ai-fitting'
      path: '/ai-fitting'
      fullPath: '/fashion/ai-fitting'
      preLoaderRoute: typeof AuthenticatedFashionAiFittingRouteImport
      parentRoute: typeof AuthenticatedFashionRoute
    }
    '/_authenticated/fashion/accessories': {
      id: '/_authenticated/fashion/accessories'
      path: '/accessories'
      fullPath: '/fashion/accessories'
      preLoaderRoute: typeof AuthenticatedFashionAccessoriesRouteImport
      parentRoute: typeof AuthenticatedFashionRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedFashionRouteChildren {
  AuthenticatedFashionAccessoriesRoute: typeof AuthenticatedFashionAccessoriesRoute
  AuthenticatedFashionAiFittingRoute: typeof AuthenticatedFashionAiFittingRoute
  AuthenticatedFashionReturnsRoute: typeof AuthenticatedFashionReturnsRoute
}

const AuthenticatedFashionRouteChildren: AuthenticatedFashionRouteChildren = {
  AuthenticatedFashionAccessoriesRoute: AuthenticatedFashionAccessoriesRoute,
  AuthenticatedFashionAiFittingRoute: AuthenticatedFashionAiFittingRoute,
  AuthenticatedFashionReturnsRoute: AuthenticatedFashionReturnsRoute,
}

const AuthenticatedFashionRouteWithChildren =
  AuthenticatedFashionRoute._addFileChildren(AuthenticatedFashionRouteChildren)

interface AuthenticatedHotelRouteChildren {
  AuthenticatedHotelChatRoute: typeof AuthenticatedHotelChatRoute
  AuthenticatedHotelGuestPortalRoute: typeof AuthenticatedHotelGuestPortalRoute
  AuthenticatedHotelOperationsRoute: typeof AuthenticatedHotelOperationsRoute
  AuthenticatedHotelRequestsRoute: typeof AuthenticatedHotelRequestsRoute
  AuthenticatedHotelStayRoute: typeof AuthenticatedHotelStayRoute
}

const AuthenticatedHotelRouteChildren: AuthenticatedHotelRouteChildren = {
  AuthenticatedHotelChatRoute: AuthenticatedHotelChatRoute,
  AuthenticatedHotelGuestPortalRoute: AuthenticatedHotelGuestPortalRoute,
  AuthenticatedHotelOperationsRoute: AuthenticatedHotelOperationsRoute,
  AuthenticatedHotelRequestsRoute: AuthenticatedHotelRequestsRoute,
  AuthenticatedHotelStayRoute: AuthenticatedHotelStayRoute,
}

const AuthenticatedHotelRouteWithChildren =
  AuthenticatedHotelRoute._addFileChildren(AuthenticatedHotelRouteChildren)

interface AuthenticatedVeganRouteChildren {
  AuthenticatedVeganCharityRoute: typeof AuthenticatedVeganCharityRoute
  AuthenticatedVeganOrdersRoute: typeof AuthenticatedVeganOrdersRoute
  AuthenticatedVeganPosRoute: typeof AuthenticatedVeganPosRoute
  AuthenticatedVeganProductsRoute: typeof AuthenticatedVeganProductsRoute
  AuthenticatedVeganTemplesRoute: typeof AuthenticatedVeganTemplesRoute
}

const AuthenticatedVeganRouteChildren: AuthenticatedVeganRouteChildren = {
  AuthenticatedVeganCharityRoute: AuthenticatedVeganCharityRoute,
  AuthenticatedVeganOrdersRoute: AuthenticatedVeganOrdersRoute,
  AuthenticatedVeganPosRoute: AuthenticatedVeganPosRoute,
  AuthenticatedVeganProductsRoute: AuthenticatedVeganProductsRoute,
  AuthenticatedVeganTemplesRoute: AuthenticatedVeganTemplesRoute,
}

const AuthenticatedVeganRouteWithChildren =
  AuthenticatedVeganRoute._addFileChildren(AuthenticatedVeganRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAffiliateRoute: typeof AuthenticatedAffiliateRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFashionRoute: typeof AuthenticatedFashionRouteWithChildren
  AuthenticatedHotelRoute: typeof AuthenticatedHotelRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPromosRoute: typeof AuthenticatedPromosRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
  AuthenticatedStoresRoute: typeof AuthenticatedStoresRoute
  AuthenticatedSurveyStatsRoute: typeof AuthenticatedSurveyStatsRoute
  AuthenticatedTiersRoute: typeof AuthenticatedTiersRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVeganRoute: typeof AuthenticatedVeganRouteWithChildren
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWithdrawalsRoute: typeof AuthenticatedWithdrawalsRoute
  AuthenticatedSuperAdminModulesRoute: typeof AuthenticatedSuperAdminModulesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAffiliateRoute: AuthenticatedAffiliateRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFashionRoute: AuthenticatedFashionRouteWithChildren,
  AuthenticatedHotelRoute: AuthenticatedHotelRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPromosRoute: AuthenticatedPromosRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
  AuthenticatedStoresRoute: AuthenticatedStoresRoute,
  AuthenticatedSurveyStatsRoute: AuthenticatedSurveyStatsRoute,
  AuthenticatedTiersRoute: AuthenticatedTiersRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVeganRoute: AuthenticatedVeganRouteWithChildren,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWithdrawalsRoute: AuthenticatedWithdrawalsRoute,
  AuthenticatedSuperAdminModulesRoute: AuthenticatedSuperAdminModulesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  CongSoRoute: CongSoRoute,
  DamDiChoiRoute: DamDiChoiRoute,
  DamNguRoute: DamNguRoute,
  DanhMucRoute: DanhMucRoute,
  DouyinRoute: DouyinRoute,
  GioHangRoute: GioHangRoute,
  HuongDanSizeRoute: HuongDanSizeRoute,
  LienHeRoute: LienHeRoute,
  LoginRoute: LoginRoute,
  LookbookRoute: LookbookRoute,
  MyPhamRoute: MyPhamRoute,
  ProfileRoute: ProfileRoute,
  SurveyAuditRoute: SurveyAuditRoute,
  TheThaoRoute: TheThaoRoute,
  ThucPhamRoute: ThucPhamRoute,
  TimKiemRoute: TimKiemRoute,
  VeChungToiRoute: VeChungToiRoute,
  SanPhamIdRoute: SanPhamIdRoute,
  ApiPublicBillingWebhookRoute: ApiPublicBillingWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
